[opener]
pdf_opener = [
    # thanks: https://www.reddit.com/r/linux4noobs/comments/1dbqdnl/comment/lvhjobz/
    { run = 'zathura "$@"', desc = "zathura", block = true, for = "unix" }
]

[open]
prepend_rules = [
    { mime = "application/pdf", use = ["pdf_opener", "reveal"] }
]
